vars: {
  d2-config: {
    layout-engine: elk
  }
}

Mobject

Mobject -> VMobject
Mobject -> SVG -> Text

VMobject -> Polygon
VMobject -> TipableVM

Polygon -> Rect
# Polygon -> Triangles

TipableVM -> Arc -> Circle
TipableVM -> Line
